/**
 * WordPress dependencies
 */
import { store as coreStore } from '@wordpress/core-data';
import { select, useSelect } from '@wordpress/data';
import { store as editorStore } from '@wordpress/editor';
import { useEffect, useState } from '@wordpress/element';

/**
 * Internal dependencies
 */
import type { AILabelProps } from '../types';

/**
 * Displays a label indicating that the image was generated by AI.
 *
 * @param {AILabelProps} props - Component props.
 * @return {React.JSX.Element} The AILabel component.
 */
export default function AILabel( { label }: AILabelProps ): React.JSX.Element {
	const featuredImageId =
		select( editorStore ).getEditedPostAttribute( 'featured_media' );
	const [ image, setImage ] = useState< any >( null );

	// Get the meta data from the featured image ID.
	const featuredImage = useSelect(
		( selectStore ) => {
			if ( ! featuredImageId ) {
				return null;
			}
			return selectStore( coreStore ).getEntityRecord(
				'postType',
				'attachment',
				featuredImageId
			);
		},
		[ featuredImageId ]
	);

	// Sync image state when entity record becomes available.
	useEffect( () => {
		if ( featuredImage ) {
			setImage( featuredImage );
		} else if ( ! featuredImageId ) {
			setImage( '' );
		}
	}, [ featuredImage, featuredImageId ] );

	return (
		<>
			{ image && image?.meta?.wpai_generated === 1 && (
				<div className="ai-label">
					<span
						className="ai-label__text"
						style={ { color: '#757575' } }
					>
						{ label }
					</span>
				</div>
			) }
		</>
	);
}
